### PR TITLE
Refactor YuccaConfigurator PS and BS handling, remove CPU case

### PR DESCRIPTION
**Pull request by jakobamb**
Fixed a bug in set up of batch and patch size, where, when training on CPU, a BS was set but no PS.

I went ahead and removed the whole "if not torch.cuda.is_available():" part, as it is too opionionated. The user might want to test specific PS and BS settings on CPU, and should be in charge of making appropriate settings when running CPU training

### CODE REVIEW

**Comment by jakobamb** [comment]
@Sllambias could you take a look at this if you have time? :) Would like to discuss the removal of the CPU case, and I think we have to update the test 001 dataset

**Comment by Sllambias** [comment]
I don't mind removing the CPU case. It was mostly there to allow debugging other parts on CPU without running into OOM issues, however the "tiny_patch" solves this issue too, as long as it will also include a fixed batch size. 
Out of curiosity: will you run anything real on the CPU ever?

**Comment by Sllambias** [comment]
I also like to have an "else" in the end of IF statements like this to clearly catch any strays. Otherwise debugging can be very hard if for some reason the pipeline can run without this successfully configuring anything

**Comment by jakobamb** [comment]
After yuccalib reintegration:

Do we really need num_classes in find_optimal_tensor_dims @Sllambias

**Comment by jakobamb** [comment]
#44

**Review by Sllambias — APPROVED** [review]

**Pull request merged**
