### PR TITLE
Separate Split Config Module

### PR DESCRIPTION
**Pull request by asbjrnmunk**
As thoroughly discussed at the office today 🧓

### CODE REVIEW

**Comment by Sllambias** [comment]
Lovely! This looks nice and understandable.
I have two comments. One is that I would prefer to not have hardcoded variables in the files if possible, such as the seed and the accepted methods. I think both could also just be default values in your function.
The other is that I really think we can completely remove the method argument as I feel like everything we want can be achieved using a combination of val_ratio and K. We can then set K's default to 1 (or 5 if you would prefer that) and the "simple" method would just be the default

**Review by Sllambias — COMMENTED** [review]
Lovely! This looks nice and understandable.
I have two comments. One is that I would prefer to not have hardcoded variables in the files if possible, such as the seed and the accepted methods. I think both could also just be default values in your function.
The other is that I really think we can completely remove the method argument as I feel like everything we want can be achieved using a combination of val_ratio and K. We can then set K's default to 1 (or 5 if you would prefer that) and the "simple" method would just be the default

**Comment by asbjrnmunk** [comment]
Good points!

Ad 1) You are right, I will make the constants part of the code and not global.
Ad 2) The problem with not having a method string is that we will not be able to provide what we agreed yesterday of "configurable with good defaults" since the default value of `val_ratio` and/or `k` has to be `None`, while with a method parameter we can have default parameters for both, without reducing configurability. I also find it easier to understand that this function is able to provide two different splitting methods when you have a method argument, while you would have to consult the documentation if you were simply provided a `k` and a `val_ratio` parameter -- they could do many things!

**Comment by Sllambias** [comment]
Hm. I don't think we're doing 2 different splitting methods. I think we're just doing K-Fold with different values. What you're doing seems like 1-fold val with a low val_ratio while I do 5-fold val with a higher val_ratio. So to me it sort of feels like we're introducing a string argument that let's us achieve the same things we can without it. Do you have an example of something you can do with the method but not with just k and val_ratio?

**Comment by asbjrnmunk** [comment]
I disagree that `simple` is just `kfold` with `k = 1`. In `kfold` the idea is that any fold can be both training and validation which makes sense since because each fold is the exact same size. In `simple` we explicitly change this to make it highly unevenly sized, such that we have x% of the data as validation samples and 100-x% training examples. If do as you propose, I would expect that the code base would be very difficult for newcomers to understand since they expect kfold to function a specific way. 

From scikitlearn:
`KFold` divides all the samples in  groups of samples, called folds, **of equal sizes** (if possible).

From Wikipedia:
In k-fold cross-validation, the original sample is randomly partitioned into k **equal sized subsamples**, often referred to as "folds".

**Comment by asbjrnmunk** [comment]
Actually, one more point is that there is no such thing as `1-fold`. That would give you no validation split.

**Comment by asbjrnmunk** [comment]
I have updated the code and there is no longer a `method` string, but we will have nice defaults by suggesting 5fold

**Review by Sllambias — APPROVED** [review]

**Review by Sllambias — APPROVED** [review]

**Review by jakobamb — APPROVED** [review]
lgtm

**Pull request merged**
