### PR TITLE
Allow for tiny split

### PR DESCRIPTION
**Pull request by asbjrnmunk**
I have 28000 datapoints and thus only need a tiny validation split and one split is fine. This PR implements that.

### CODE REVIEW

**Comment by Sllambias** [comment]
Haven't read 100% of this so if it's already there you should ignore this: I think we should maybe have documentation somewhere if splits are created using specific methods (like "tiny_val") and also I think it should have a reproducible/fixed seed so others can generate identical splits (I realize in your case this might not be super relevant with >100k cases, but it's pretty important in small datasets)

**Review by jakobamb — CHANGES_REQUESTED** [review]
deferred for discussion with @Sllambias regarding decoupling functionality of the Configurator

**Comment by asbjrnmunk** [comment]
Bring coffee @Sllambias ☕

**Comment by asbjrnmunk** [comment]
Closed as changes are now part of #48

**Pull request closed without merging**
